CREATE TABLE abc1d_1801_1810 (
  `id` int NOT NULL AUTO_INCREMENT,
  `folio` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `acta` int DEFAULT NULL,
  `fecha` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `edad` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nombre` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sexo_cd` varchar(1) DEFAULT NULL,
  `naturaleza` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `padres` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `conyuges` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `parroco` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `notas` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `entierro` varchar(5) DEFAULT NULL,
  `tramo` int DEFAULT '0',
  `testamento_ind` int DEFAULT NULL,
  `parr_cd` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'ABAA' COMMENT 'Código representando parroquias en DIM_PARROQUIAS',
  `rango_etario` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Grupos de edades usado en algunas publicaciones de la Sociedad Puertorriqueña de Genealogía',
  `grupo_etario` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Ciclos de vida:\\nInfancia 0-10 años\\nAdolescencia 11-17 años\\nJuventud 18-35 años\\nAdultez 36-65 años\\nAncianidad >= 66 años ',
  `ciudad_pais` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Nombre normalizado de la ciudad o el país de naturaleza',
  `apellido_norm` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Apellido normalizado del difunto',
  `cal_daily_key` decimal(8,0) DEFAULT NULL COMMENT 'Clave de fachas para usar cualquier de los calendarios en esta base de datos',
  `create_ts` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_ts` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `complete_ind` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
